"""Generates web/packages/domain/src/catalogs/banks.ts from src/opesvault/catalogs/banks.py.

    uv run python scripts/gerar_bancos_ts.py

The desktop list (refreshed by scripts/atualizar_bancos.py) is the source; the web domain embeds
the same rows so both apps name the same banks. The result is formatted with the web workspace's
Prettier when it is installed (otherwise run `pnpm format` in web/).
"""

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
TARGET = WEB / "packages" / "domain" / "src" / "catalogs" / "banks.ts"


def main() -> int:
    sys.path.insert(0, str(ROOT / "src"))
    from opesvault.catalogs.banks import BANKS, UPDATED

    lines = [
        "/**",
        " * Brazilian banks and payment institutions with a COMPE code. Port of `catalogs/banks.py`.",
        " *",
        " * GENERATED by scripts/gerar_bancos_ts.py from src/opesvault/catalogs/banks.py: do not edit.",
        " * Source: github.com/guibranco/BancosBrasileiros (public domain), from the Banco Central's lists.",
        " */",
        "",
        f"export const UPDATED = {json.dumps(UPDATED)};",
        "",
        "/** (COMPE, ISPB, CNPJ digits or '', short name, full name) */",
        "export type BankRow = readonly [code: string, ispb: string, cnpj: string, shortName: string, name: string];",
        "",
        "export const BANKS: readonly BankRow[] = [",
    ]
    lines += [f"  {json.dumps(list(row), ensure_ascii=False)}," for row in BANKS]
    lines.append("];")
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")
    prettier = WEB / "node_modules" / ".bin" / ("prettier.cmd" if sys.platform == "win32" else "prettier")
    if prettier.exists():
        subprocess.run([str(prettier), "--write", str(TARGET)], cwd=WEB, check=True)
    else:
        print("Prettier não encontrado: rode `pnpm format` em web/")
    print(f"{len(BANKS)} instituições em {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
