"""Writes the synthetic documents the web demo imports as a TypeScript module.

    uv run python scripts/web_demo_docs.py && (cd web && pnpm exec prettier --write packages/domain/src/demo_docs)

The bytes come from tests/synthetic_docs.py (all names and values are fictitious); the output,
`web/packages/domain/src/demo_docs/index.ts`, is committed so the web app needs no Python.
"""

import base64
from pathlib import Path

from tests import synthetic_docs as docs

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "web" / "packages" / "domain" / "src" / "demo_docs" / "index.ts"

DOCUMENTS = [
    ("NUBANK_CARD_PDF", "Fatura de cartão Nubank (PDF)", docs.nubank_card_pdf),
    ("ITAU_CARD_PDF", "Fatura de cartão Itaú (PDF, duas páginas)", docs.itau_card_pdf),
    ("BRADESCO_CARD_PDF", "Fatura de cartão Bradesco (PDF)", docs.bradesco_card_pdf),
    ("ITAU_BANK_PDF", "Extrato de conta corrente Itaú (PDF)", docs.itau_bank_pdf),
    ("NUBANK_ACCOUNT_CSV", "Extrato da conta Nubank (CSV)", docs.nubank_account_csv),
    ("NUBANK_CARD_CSV", "Fatura do cartão Nubank (CSV)", docs.nubank_card_csv),
    ("BANK_OFX", "Extrato bancário (OFX)", docs.ofx_bank),
    ("SINACOR_NOTE_PDF", "Nota de negociação SINACOR (PDF)", docs.sinacor_note_pdf),
    ("BANK_INCOME_REPORT_PDF", "Informe de rendimentos de banco (PDF)", docs.bank_income_report_pdf),
]


def main() -> None:
    lines = [
        "/**",
        " * Synthetic documents for the demo project (fictitious names and values).",
        " * Generated by scripts/web_demo_docs.py from tests/synthetic_docs.py; do not edit by hand.",
        " */",
        "",
        "function bytes(base64: string): Uint8Array {",
        "  return Uint8Array.from(atob(base64), (c) => c.charCodeAt(0));",
        "}",
        "",
    ]
    for name, what, build in DOCUMENTS:
        encoded = base64.b64encode(build()).decode()
        lines.append(f"/** {what}. */")
        lines.append(f'export const {name} = bytes("{encoded}");')
        lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
